export enum ErrorEnum {
  DEFAULT = '0:Erreur inconnue',
  SERVER_ERROR = '500:Service occupé, veuillez réessayer plus tard',

  SYSTEM_USER_EXISTS = '1001:L\'utilisateur système existe déjà',
  INVALID_VERIFICATION_CODE = '1002:Le code de vérification est incorrect',
  INVALID_USERNAME_PASSWORD = '1003:Nom d\'utilisateur ou mot de passe incorrect',
  NODE_ROUTE_EXISTS = '1004:La route du nœud existe déjà',
  PERMISSION_REQUIRES_PARENT = '1005:L\'autorisation doit inclure un nœud parent',
  ILLEGAL_OPERATION_DIRECTORY_PARENT = '1006:Opération illégale : ce nœud ne prend en charge que les nœuds parents de type répertoire',
  ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '1007:Opération illégale : le type de nœud ne peut pas être converti directement',
  ROLE_HAS_ASSOCIATED_USERS = '1008:Ce rôle a des utilisateurs associés, veuillez d\'abord supprimer les utilisateurs associés',
  DEPARTMENT_HAS_ASSOCIATED_USERS = '1009:Ce département a des utilisateurs associés, veuillez d\'abord supprimer les utilisateurs associés',
  DEPARTMENT_HAS_ASSOCIATED_ROLES = '1010:Ce département a des rôles associés, veuillez d\'abord supprimer les rôles associés',
  PASSWORD_MISMATCH = '1011:L\'ancien mot de passe ne correspond pas au mot de passe original',
  LOGOUT_OWN_SESSION = '1012:Pour vous déconnecter, utilisez le bouton de déconnexion en haut à droite',
  NOT_ALLOWED_TO_LOGOUT_USER = '1013:La déconnexion de cet utilisateur n\'est pas autorisée',
  PARENT_MENU_NOT_FOUND = '1014:Le menu parent n\'existe pas',
  DEPARTMENT_HAS_CHILD_DEPARTMENTS = '1015:Ce département a des sous-départements, veuillez d\'abord supprimer les sous-départements',
  SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '1016:Les fonctions intégrées du système ne peuvent pas être modifiées',
  USER_NOT_FOUND = '1017:L\'utilisateur n\'existe pas',
  UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '1018:Impossible de trouver le département de l\'utilisateur actuel',
  DEPARTMENT_NOT_FOUND = '1019:Le département n\'existe pas',
  PARAMETER_CONFIG_KEY_EXISTS = '1022:La paire clé-valeur de configuration de paramètre existe déjà',
  DEFAULT_ROLE_NOT_FOUND = '1023:Le rôle par défaut attribué n\'existe pas',

  INVALID_LOGIN = '1101:Connexion invalide, veuillez vous reconnecter',
  NO_PERMISSION = '1102:Accès non autorisé',
  ONLY_ADMIN_CAN_LOGIN = '1103:Non administrateur, connexion impossible',
  REQUEST_INVALIDATED = '1104:La requête actuelle a expiré',
  ACCOUNT_LOGGED_IN_ELSEWHERE = '1105:Votre compte est connecté depuis un autre emplacement',
  GUEST_ACCOUNT_RESTRICTED_OPERATION = '1106:Le compte invité ne permet pas cette opération',
  REQUESTED_RESOURCE_NOT_FOUND = '1107:La ressource demandée n\'existe pas',

  TOO_MANY_REQUESTS = '1201:Requêtes trop fréquentes, veuillez réessayer dans une minute',
  MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '1202:Maximum 5 codes de vérification par jour',
  VERIFICATION_CODE_SEND_FAILED = '1203:Échec de l\'envoi du code de vérification',

  INSECURE_MISSION = '1301:Tâche non sécurisée, assurez-vous d\'ajouter l\'annotation @Mission',
  EXECUTED_MISSION_NOT_FOUND = '1302:La tâche exécutée n\'existe pas',
  MISSION_EXECUTION_FAILED = '1303:Échec de l\'exécution de la tâche',
  MISSION_NOT_FOUND = '1304:La tâche n\'existe pas',

  // Lié à OSS
  OSS_FILE_OR_DIR_EXIST = '1401:Le fichier ou le répertoire à créer existe déjà',
  OSS_NO_OPERATION_REQUIRED = '1402:Aucune opération nécessaire',
  OSS_EXCEE_MAXIMUM_QUANTITY = '1403:La quantité maximale de traitement prise en charge a été dépassée',
}
